name: Random Changes

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 30 minutes

jobs:
  random_change:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Random Changes Script
      run: python random_changes.py

    - name: Commit and Push Changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Random change at $(date)"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/AK2k30/linkedin-X-post-auto-cli.git HEAD:main
